from .family import Family

hiraganasSet: dict[Family, dict[str, str]] = {
    Family.BASIC: {
        'あ': 'A',
        'い': 'I',
        'う': 'U',
        'え': 'E',
        'お': 'O',
        'か': 'KA',
        'き': 'KI',
        'く': 'KU',
        'け': 'KE',
        'こ': 'KO',
        'さ': 'SA',
        'し': 'SHI',
        'す': 'SU',
        'せ': 'SE',
        'そ': 'SO',
        'た': 'TA',
        'ち': 'CHI',
        'つ': 'TSU',
        'て': 'TE',
        'と': 'TO',
        'な': 'NA',
        'に': 'NI',
        'ぬ': 'NU',
        'ね': 'NE',
        'の': 'NO',
        'は': 'HA',
        'ひ': 'HI',
        'ふ': 'FU',
        'へ': 'HE',
        'ほ': 'HO',
        'ま': 'MA',
        'み': 'MI',
        'む': 'MU',
        'め': 'ME',
        'も': 'MO',
        'ら': 'RA',
        'り': 'RI',
        'る': 'RU',
        'れ': 'RE',
        'ろ': 'RO',
        'や': 'YA',
        'ゆ': 'YU',
        'よ': 'YO',
        'わ': 'WA',
        'ゐ': 'WI',
        'ゑ': 'WE',
        'を': 'WO',
        'ん': 'N'
    },
    Family.COMPLEXE: {}
}